apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: infoscreen-server
  name: infoscreen-server
  namespace: infoscreen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infoscreen-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: infoscreen-server
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: infoscreen-config
        image: ghcr.io/knorr3/infoscreen:main
        imagePullPolicy: Always
        name: infoscreen
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ghcr-pull-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
